services: 
  app:
    image: todo-app
    command: sh -c "yarn install && yarn run dev"
    ports: 
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todoappDB

  mysql:
    image: mysql:8.0
    volumes: 
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todoappDB

volumes: 
  todo-mysql-data:
  
